### PR TITLE
Add xicon #94

### LINKED ISSUE #94: Add close buttons to table of contents and settings

### PR DESCRIPTION
**Pull request by ricardoom**
fixes #94

### CODE REVIEW

**Comment by aslagle** [comment]
I want to write some more tests before we merge this.

**Comment by ricardoom** [comment]
getting merge conflicts too... I'll see about fixing

**Comment by ricardoom** [comment]
werid. no merge conflicts locally...

**Comment by aslagle** [comment]
I added most of the tests I wanted but I couldn't get keyboard focus to work in tests so there's still nothing for that.

**Review by aslagle — APPROVED** [review]
I think this is ready to merge if willa's happy with it.

**Comment by ricardoom** [comment]
@aslagle cool...

**Comment by aslagle** [comment]
@ricardoom I made one more tiny change, could you make sure it still looks ok?

**Comment by ricardoom** [comment]
👁

**Comment by ricardoom** [comment]
I think all is well here. ready to merge.

**Pull request merged**
