### PR TITLE
Pre-loading screen and async book chapter loading

### PR DESCRIPTION
**Pull request by hokei**
this PR does two things:  
1) Fetches all the book resources at once, rather than fetching them one at a time
2) Puts the loading spinner while resources are fetching.  (The delay is an old artifact, do you think it is a good idea to show the spinner right away?) 

I tried it with a few books, but please try it with a few more to help me verify that this all actually works!

### CODE REVIEW

**Comment by hokei** [comment]
navigating between chapters with arrows seems to not be working, will look into this in a bit

**Review by kristojorg — APPROVED** [review]
This is really really good. Speeds up load times for me by a lot! I think the next step is a loading indicator in CPW on the `/read` page (this will get rid of the blank screen before the axisnow loader shows up I think).

I don't fully understand the code obviously, but I didn't see anything glaring. 

The one book that didn't work for me is "Exile for Dreamers", but I just checked and it also doesn't work on beta

**Comment by kristojorg** [comment]
Does this need a changelog though?

**Comment by hokei** [comment]
Oh of course!

**Pull request merged**
