### PR TITLE
PR for edrlab (jellybooks) changes

### PR DESCRIPTION
**Pull request by hokei**
Getting master caught up.

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
Does this PR include your latest updates? We don't want to merge into `master` just yet but wanted to keep `development` the working branch until others know what is going on. Maybe it's too late now but is there a way to do a PR from the working branch into `development`?

**Comment by hokei** [comment]
@EdwinGuzman No, this doesn't include the latest updates.  I can me to close this up, push master onto development, and then make a PR from merge-edrlab-changes onto development!  It will require some force-pushing, but development wasn't a branch that existed before this PR, so it should be ok...?

**Comment by EdwinGuzman** [comment]
Right, `development` didn't exist before. What did you branch off from to create `development`? How about you branch off `master` and create a `develop` branch, make a PR from `merge-edrlab-changes` to `develop`, and then the updates you did can be a PR into `develop` after that. `develop` can be our working branch, if `development` doesn't work, for a while until we are ready to merge to `master` for a new version. @adriana-alter what do you think?

**Comment by adriana-alter** [comment]
That sounds like a good plan to me!

**Comment by hokei** [comment]
@EdwinGuzman I had branched off `merge-edrlab-changes` to create `development`, but I've created the new PR, which works better!

**Pull request closed without merging**
