### PR TITLE
Scrolling suggestion for screen readers/keyboard nav and tab index fixes

### LINKED ISSUE #44: Add message that scrolling view is recommended for screen readers.

### LINKED ISSUE #46: In settings, there's no way to tell which view is selected from a screen reader.

### LINKED ISSUE #48: Make it easier to get to the navigation elements from a screen reader
The contents and settings menus at the top from JAWS, and the chapter buttons at the bottom from any screen reader.

### LINKED ISSUE #78: When using keyboard navigation, tabbing goes through all TOC links even when TOC is closed

### PR DESCRIPTION
**Pull request by aslagle**
This fixes #44 
This fixes #78 
This fixes #48 
This fixes #46

I added a message as the first tab item on the page that says 
```
We recommend scrolling mode for use with screen readers and keyboard navigation.
Go to settings to switch to scrolling mode.
```
and links to the button that opens the settings menu. 

In addition, I fixed the tab index on links and buttons in the menus so that it's 0 when the menu is displayed and -1 when the menu is hidden.

### CODE REVIEW

**Review by ricardoom — APPROVED** [review]
i'm pretty sure this is good to go. and hopefully will merge nicely w/ #93 :crossed_fingers:

**Comment by aslagle** [comment]
This breaks the code I had to automatically show the bottom chapter nav when you scroll to the bottom.

**Comment by aslagle** [comment]
I'm also tabbing through the TOC when it's hidden again.

**Comment by ricardoom** [comment]
ok. will reject this and re-add the changes i made more granularly on this branch to see where they conflict.

**Comment by aslagle** [comment]
I'm not sure if it's from your changes or mine @ricardoom, I'll look into it too.

**Comment by aslagle** [comment]
The tabbing problem might have been a fluke... It seems okay when I don't have dev tools open.

**Comment by aslagle** [comment]
I think this looks fine now. Going to put the updates on qa so we can test more before merging though.

**Pull request merged**
